dirs:
  - content
useGitIgnore: true
ignorePatterns:
  - pattern: "^/.*" # local links are not checked
  - pattern: "^http://localhost.*" # Localhost links are not checked
  - pattern: "^https://packagecontrol\.io.*" # Package control links are not checked (it was 500ing at time of writing)
fileExtensions:
  - mdx
  - md
modifiedFilesOnly: false
aliveStatusCodes:
  - 200
  - 201
  - 204
