dirs:
  - content
useGitIgnore: true
ignorePatterns:
  - pattern: "^http://localhost.*"
  - pattern: "^/.*"
fileExtensions:
  - mdx
  - md
modifiedFilesOnly: false
aliveStatusCodes:
  - 200
  - 201
  - 204
