name: Check MDX links

on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "no"
          folder-path: "content"
          file-extension: ".mdx"
          config-file: ".github/workflows/linkcheck_config.json"
